{% set name = "django-polymorphic-tree" %}
{% set version = "2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-polymorphic-tree-{{ version }}.tar.gz
  sha256: a6d40c2ef350c5a50bd83727ca8cba85088890a7a08a106caeb3c5dc5ae072aa

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - django
    - pip
    - python {{ python_min }}
  run:
    - django
    - django-mptt >=0.8.0
    - django-tag-parser >=2.1
    - django_polymorphic >=1.3
    - future >=0.12.2
    - python >={{ python_min }}

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-polymorphic/django-polymorphic-tree
  summary: A polymorphic mptt structure to display content in a tree.
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - hadim
