{% set name = "django-polymorphic-tree" %}
{% set version = "2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-polymorphic-tree-{{ version }}.tar.gz
  sha256: 16ecaed9d3fc65adb36463d5d9aca4fb33fad52fcf2300fb6f2c70124af3b72a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - django
    - pip
    - python >=3.6
  run:
    - django
    - django-mptt >=0.8.0
    - django-tag-parser >=2.1
    - django_polymorphic >=1.3
    - future >=0.12.2
    - python >=3.6

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-polymorphic/django-polymorphic-tree
  summary: A polymorphic mptt structure to display content in a tree.
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - hadim
